services:
  frontend:
    build:
      context: .
      args:
        VITE_POCKETBASE_URL: ${VITE_POCKETBASE_URL:-http://127.0.0.1:8090}
    ports:
      - "8080:80"
    environment:
      - VITE_POCKETBASE_URL=http://127.0.0.1:8090
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.23.12
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data

volumes:
  pocketbase_data:
